//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDVDroidElgin {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PDVDroidElgin.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;det nItem=&quot;1&quot;&gt;
        ///    &lt;prod&gt;
        ///        &lt;cProd&gt;1&lt;/cProd&gt;
        ///        &lt;cEAN&gt;SEM GTIN&lt;/cEAN&gt;
        ///        &lt;xProd&gt;@produto&lt;/xProd&gt;
        ///        &lt;NCM&gt;01022911&lt;/NCM&gt;
        ///        &lt;cBenef&gt;1234567890&lt;/cBenef&gt;
        ///        &lt;CFOP&gt;5102&lt;/CFOP&gt;
        ///        &lt;uCom&gt;UN&lt;/uCom&gt;
        ///        &lt;qCom&gt;@quant&lt;/qCom&gt;
        ///        &lt;vUnCom&gt;@vUnit&lt;/vUnCom&gt;
        ///        &lt;vProd&gt;@totalItem&lt;/vProd&gt;
        ///        &lt;cEANTrib&gt;SEM GTIN&lt;/cEANTrib&gt;
        ///        &lt;uTrib&gt;UN&lt;/uTrib&gt;
        ///        &lt;qTrib&gt;@totalItem&lt;/qTrib&gt;
        ///        &lt;vUnTrib&gt;@vUnit&lt;/vUnTrib&gt;
        ///        &lt;indTot&gt;1&lt;/indTot&gt;
        ///    &lt;/prod&gt;
        ///    &lt;imposto&gt;
        ///      [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string detalhesNFCe {
            get {
                return ResourceManager.GetString("detalhesNFCe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;nfeProc versao=&quot;4.00&quot; xmlns=&quot;http://www.portalfiscal.inf.br/nfe&quot;&gt;
        ///    &lt;NFe xmlns=&quot;http://www.portalfiscal.inf.br/nfe&quot;&gt;
        ///        &lt;infNFe versao=&quot;4.00&quot; Id=&quot;NFe33180705481336000137651000000916401000005909&quot;&gt;
        ///            &lt;ide&gt;
        ///                &lt;cUF&gt;33&lt;/cUF&gt;
        ///                &lt;cNF&gt;00000590&lt;/cNF&gt;
        ///                &lt;natOp&gt;VENDA CONSUMIDOR&lt;/natOp&gt;
        ///                &lt;mod&gt;65&lt;/mod&gt;
        ///                &lt;serie&gt;100&lt;/serie&gt;
        ///                &lt;nNF&gt;@num&lt;/nNF&gt;
        ///                &lt;dhEmi&gt;@data&lt;/dhEmi&gt;
        ///    [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string xmlnfce {
            get {
                return ResourceManager.GetString("xmlnfce", resourceCulture);
            }
        }
    }
}
